### ISSUE TITLE
7. As a player, I want to hear sounds when I start/win the game.

### ISSUE THREAD

**Issue by pinzimpossible** [DragonHeartZz/Assign#22]
Tìm cách thêm âm thanh vào trong game (3 giờ)
Tìm file âm thanh (10 phút)
Thử nghiệm (1 giờ)
Thảo luận (1 giờ)
Làm thực tế (1 giờ)
Kiểm tra lại so với yêu cầu (30 phút)
Làm lại nếu sai (45 phút)
Submit và report (10 phút)

**Comment by DragonHeartZz** [comment]
Tìm cách thêm âm thanh vào trong game : 30 phút
Tìm file âm thanh : 30 phút
Thử nghiệm :  1 giờ
Thảo luận: 10 phút
Làm thực tế : 1 tiếng
Kiểm tra lại so với yêu cầu: 10 phút
Làm lại : 30 phút
Submit và report: 10 phút
Tổng : 3 tiếng 50 phút
